### ISSUE TITLE
Howto search by country name in admin

### ISSUE THREAD

**Issue by mwolff44** [SmileyChris/django-countries#306] opened 2020-05-25 18:14 UTC
Hi,
I need to implement a feature to search in admin list view the name of country. I am able to search the code (ISO2) but not by name.
How can i acheive this ?
regards
Mathias

**Comment by SmileyChris** [comment] 2020-05-26 02:28
Duplicate of #242 -- currently not a thing, but if someone wants to have a go at implementation if they want.

**Closed by SmileyChris** 2020-05-26 02:28 UTC
